
-- Inserting entries for table books
INSERT INTO `books`( `bookName`, `bookPrice`, `authorName`, `bookImage`, `bookDescription`, `featured`) 
VALUES ('If Tomorrow Comes','49.99','Sidney Sheldon','/Webapps/Exercises/Project1/images/if_tommorow_comes.jpg','If tomorrow comes is classic crime thriller novel by Sidney Sheldon.  ',' 1 ');

INSERT INTO `books`( `bookName`, `bookPrice`, `authorName`, `bookImage`, `bookDescription`, `featured`) 
VALUES (' An Abundance of Katherines ',' 32.87 ',' John Green ',' /Webapps/Exercises/Project1/images/an_abundance_of_kathrine.jpg ',' Its a romantic novel by john green  ',' 1 ');

INSERT INTO `books`( `bookName`, `bookPrice`, `authorName`, `bookImage`, `bookDescription`, `featured`) 
VALUES (' Paper Towns ',' 19.45 ',' John Green ',' /Webapps/Exercises/Project1/images/paper_towns.jpg ',' Another romantic masterpiece by john green  ',' 2 ');

INSERT INTO `books`( `bookName`, `bookPrice`, `authorName`, `bookImage`, `bookDescription`, `featured`) 
VALUES (' The Phoenix ',' 35.99 ',' Sidney Sheldon ',' /Webapps/Exercises/Project1/images/the_phoenix.jpg ','   ',' 1 ');

INSERT INTO `books`( `bookName`, `bookPrice`, `authorName`, `bookImage`, `bookDescription`, `featured`) 
VALUES (' ABC Murders ',' 32.87 ',' Agatha Christie ',' /Webapps/Exercises/Project1/images/abc.jpg ','   ',' 1 ');

INSERT INTO `books`( `bookName`, `bookPrice`, `authorName`, `bookImage`, `bookDescription`, `featured`) 
VALUES (' Bloodline ',' 29.99 ',' Sidney Sheldon ',' /Webapps/Exercises/Project1/images/bloodline.jpg ',' bloodline is classic crime thriller novel by Sidney Sheldon.   ',' 2 ');

INSERT INTO `books`( `bookName`, `bookPrice`, `authorName`, `bookImage`, `bookDescription`, `featured`) 
VALUES (' Jane Eyre ',' 29.99 ',' Charlotte Bronte ',' /Webapps/Exercises/Project1/images/jane_eyre.jpg ','   ',' 2 ');

-- Inserting entries for table bookstoreinventory
INSERT INTO `bookstoreinventory`(`bookID`, `bookQuantity`) VALUES ('1','10');
INSERT INTO `bookstoreinventory`(`bookID`, `bookQuantity`) VALUES ('2','10');
INSERT INTO `bookstoreinventory`(`bookID`, `bookQuantity`) VALUES ('3','10');
INSERT INTO `bookstoreinventory`(`bookID`, `bookQuantity`) VALUES ('4','10');
INSERT INTO `bookstoreinventory`(`bookID`, `bookQuantity`) VALUES ('5','10');
INSERT INTO `bookstoreinventory`(`bookID`, `bookQuantity`) VALUES ('6','10');
INSERT INTO `bookstoreinventory`(`bookID`, `bookQuantity`) VALUES ('7','10');