INSERT INTO `books` (`bookID`, `bookName`, `bookPrice`, `authorName`, `bookImage`, `bookDescription`, `featured`) VALUES (NULL, 'If Tomorrow Comes', '49.99', 'Sidney Sheldon', '/Webapps/Exercises/Project1/images/if_tommorrow_comes.jpg', 'If tomorrow comes is classic crime thriller novel by Sidney Sheldon. ', '1');

INSERT INTO `books` (`bookID`, `bookName`, `bookPrice`, `authorName`, `bookImage`, `bookDescription`, `featured`) VALUES (NULL, 'An Abundance of Katherines', '32.87', 'John Green', '/Webapps/Exercises/Project1/images/an_abundance_of_kathrine.jpg', 'Its a romantic novel by john green', '2');

INSERT INTO `books` (`bookID`, `bookName`, `bookPrice`, `authorName`, `bookImage`, `bookDescription`, `featured`) VALUES (NULL, 'Paper Towns', '19.45', 'John Green', '/Webapps/Exercises/Project1/images/paper_towns.jpg', 'Another romantic masterpiece by john green', '2');

